# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://qwutony.github.io
date_format: "ordinal"
title: 
subtitle: "The Katsu Blog about Security"
description: "Just a student with an interest in security"
keywords: Tony Wu, qwutony
timezone: Australia/Melbourne
encoding: "utf-8"
since: 2024
repository: qwutony/qwutony.github.io
cdn:
    jsdelivr:
        enabled: false
# 可选组件配置
components:
    share:
        enabled: false
        hide-platforms: qq,facebook
    side_bar_repo:
        enabled: true
        limit: 5
    word_count:
        enabled: true
    qrcode:
        enabled: false
        image_alt: ""
    wiki:
        view: cate
    fancybox:
        enabled: false
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
highlight_theme: molokai

# ---------------- #
#      Author      #
# ---------------- #
author: Tony Wu
organization: 
organization_url: 
github_username: qwutony
location: Melbourne, Australia
email: qwu.tony@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Main

  -
    href: /categories/
    label: Categories

  -
    href: /archives/
    label: Archives
    mobile-hidden: true

  -
    href: /open-source/
    label: Projects
    mobile-hidden: true

  -
    href: /fragments/
    label: Fragments

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links
    mobile-hidden: true

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      INDEX       #
# ---------------- #
index:
    banner:
        # 首页 banner 区文字颜色
        color: "#fff"
        # 首页导航栏文字颜色
        nav-color: "rgba(255, 255, 255, .5)"
        # 首页 banner 区背景颜色
        background-color: "#4183c4"
        # 首页 banner 区背景图片
        # background-image: "/assets/images/octicons-bg.png"
        # background-repeat: "no-repeat"
        # background-size: "cover"

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# No comments so this section will be empty.

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    fulltext: false
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id:
    adsense:
        enabled: false
        footer: false
        sidebar: false
        sidebar-detail: false
        content_header: false
        content_footer: false
